# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be4966822f9e7e45f820009b0b2c6a8d660b6589f481d20ba15dd3a9c352c959f9c80d80949d2c7b4b7172fd204c4c293e00de14c588205c865a61440ab82783

test:
  secret_key_base: a3bfcf654e46ff9dd87fbc5647e338bbe30b1b0d96bc784a854a29fe741a1e239b6d9ad04173b40ba969408cbad324f83c04e320acae96fca40c2c4bd689a8f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
